"""first

Revision ID: a4c20fbafbcd
Revises: 
Create Date: 2021-01-22 20:21:09.603146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import types
from sqlalchemy_searchable import sync_trigger




# revision identifiers, used by Alembic.
revision = 'a4c20fbafbcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    op.create_table('text',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Unicode(length=255), nullable=True),
        sa.Column('content', sa.UnicodeText(), nullable=True),
        sa.Column('search_vector', types.ts_vector.TSVectorType(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    sync_trigger(
        conn,
        'text',
        'search_vector',
        ['content']
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text')
    # ### end Alembic commands ###
