"""second

Revision ID: b06a7167bce0
Revises:
Create Date: 2021-01-22 20:52:23.964483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_searchable import sync_trigger
from sqlalchemy_utils import types


# revision identifiers, used by Alembic.
revision = 'b06a7167bce0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('rubricks', sa.UnicodeText(), nullable=True),
    sa.Column('text', sa.UnicodeText(), nullable=True),
    sa.Column('search_vector', types.ts_vector.TSVectorType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    conn = op.get_bind()
    sync_trigger(
        conn,
        'text',
        'search_vector',
        ['text']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text')
    # ### end Alembic commands ###
